spring.application.name=demo
server.port=8081
spring.rabbitmq.addresses=amqps://uzsofyvp:bhTIMYTv9I0Zecc5a_BLbRRt4TgAvfCv@gerbil.rmq.cloudamqp.com/uzsofyvp
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration